---
- name: install vim
  become: true
  apt:
    name: vim
    state: present
- name: create vim bundles directory
  file:
    path: "/home/{{ansible_user}}/.vim/bundle"
    state: directory
- name: install vundle
  git:
    repo: "https://github.com/gmarik/Vundle.vim.git"
    dest: "/home/{{ansible_user}}/.vim/bundle/Vundle.vim"
- name: install editorconfig core
  become: true
  apt:
    name: editorconfig
    state: present
- name: install .vimrc
  copy:
    src: ".vimrc"
    dest: "/home/{{ansible_user}}/.vimrc"
  notify: install vundle plugins
